# Generated by Django 5.1.2 on 2024-10-15 14:04

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_subject_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_id',
            field=models.ForeignKey(default=app.models.Course, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='session_year_id',
            field=models.ForeignKey(default=app.models.Session_Year, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.session_year'),
        ),
    ]
