# Generated by Django 5.1.2 on 2024-10-17 09:47

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_staff_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_year_id', models.ForeignKey(default=app.models.Session_Year, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.session_year')),
                ('subject_id', models.ForeignKey(default=app.models.Session_Year, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.attendance')),
                ('student_id', models.ForeignKey(default=app.models.Session_Year, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.student')),
            ],
        ),
    ]
